import model.Move;
import model.SkillType;
import model.Wizard;
import model.World;

/**
 * Created by dragoon on 11/27/16.
 */
public class SkillsLearning {

	public static SkillType[] currentSkillsToLearn;

	public static final SkillType[] FIRE_RANGE_MOVEMENT = new SkillType[]{
			SkillType.STAFF_DAMAGE_BONUS_PASSIVE_1,
			SkillType.STAFF_DAMAGE_BONUS_AURA_1,
			SkillType.STAFF_DAMAGE_BONUS_PASSIVE_2,
			SkillType.STAFF_DAMAGE_BONUS_AURA_2,
			SkillType.FIREBALL,
			SkillType.RANGE_BONUS_PASSIVE_1,
			SkillType.RANGE_BONUS_AURA_1,
			SkillType.RANGE_BONUS_PASSIVE_2,
			SkillType.RANGE_BONUS_AURA_2,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_1,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_1,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_2,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_2,
			SkillType.HASTE,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_2,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_2,
			SkillType.SHIELD};

	public static final SkillType[] FROST_MOVEMENT_RANGE = new SkillType[]{
			SkillType.MAGICAL_DAMAGE_BONUS_PASSIVE_1,
			SkillType.MAGICAL_DAMAGE_BONUS_AURA_1,
			SkillType.MAGICAL_DAMAGE_BONUS_PASSIVE_2,
			SkillType.MAGICAL_DAMAGE_BONUS_AURA_2,
			SkillType.FROST_BOLT,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_1,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_1,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_2,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_2,
			SkillType.HASTE,
			SkillType.RANGE_BONUS_PASSIVE_1,
			SkillType.RANGE_BONUS_AURA_1,
			SkillType.RANGE_BONUS_PASSIVE_2,
			SkillType.RANGE_BONUS_AURA_2,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_2,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_2,
			SkillType.SHIELD};

	public static final SkillType[] RANGE_FIRE_MOVEMENT = new SkillType[]{
			SkillType.RANGE_BONUS_PASSIVE_1,
			SkillType.RANGE_BONUS_AURA_1,
			SkillType.RANGE_BONUS_PASSIVE_2,
			SkillType.RANGE_BONUS_AURA_2,
			SkillType.ADVANCED_MAGIC_MISSILE,
			SkillType.STAFF_DAMAGE_BONUS_PASSIVE_1,
			SkillType.STAFF_DAMAGE_BONUS_AURA_1,
			SkillType.STAFF_DAMAGE_BONUS_PASSIVE_2,
			SkillType.STAFF_DAMAGE_BONUS_AURA_2,
			SkillType.FIREBALL,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_1,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_1,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_2,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_2,
			SkillType.HASTE,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_2,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_2,
			SkillType.SHIELD};

	public static final SkillType[] MOVEMENT_FROST_RANGE = new SkillType[]{
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_1,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_1,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_2,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_2,
			SkillType.HASTE,
			SkillType.MAGICAL_DAMAGE_BONUS_PASSIVE_1,
			SkillType.MAGICAL_DAMAGE_BONUS_AURA_1,
			SkillType.MAGICAL_DAMAGE_BONUS_PASSIVE_2,
			SkillType.MAGICAL_DAMAGE_BONUS_AURA_2,
			SkillType.FROST_BOLT,
			SkillType.RANGE_BONUS_PASSIVE_1,
			SkillType.RANGE_BONUS_AURA_1,
			SkillType.RANGE_BONUS_PASSIVE_2,
			SkillType.RANGE_BONUS_AURA_2,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_2,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_2,
			SkillType.SHIELD};

	public static final SkillType[] SHIELD_FIRE_RANGE = new SkillType[]{
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_1,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_PASSIVE_2,
			SkillType.MAGICAL_DAMAGE_ABSORPTION_AURA_2,
			SkillType.SHIELD,
			SkillType.STAFF_DAMAGE_BONUS_PASSIVE_1,
			SkillType.STAFF_DAMAGE_BONUS_AURA_1,
			SkillType.STAFF_DAMAGE_BONUS_PASSIVE_2,
			SkillType.STAFF_DAMAGE_BONUS_AURA_2,
			SkillType.FIREBALL,
			SkillType.RANGE_BONUS_PASSIVE_1,
			SkillType.RANGE_BONUS_AURA_1,
			SkillType.RANGE_BONUS_PASSIVE_2,
			SkillType.RANGE_BONUS_AURA_2,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_1,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_1,
			SkillType.MOVEMENT_BONUS_FACTOR_PASSIVE_2,
			SkillType.MOVEMENT_BONUS_FACTOR_AURA_2,
			SkillType.HASTE};

	public static final SkillType[][] arraySkillsToLearn = new SkillType[][]{
			FIRE_RANGE_MOVEMENT,
			RANGE_FIRE_MOVEMENT,
			FROST_MOVEMENT_RANGE,
			MOVEMENT_FROST_RANGE,
			SHIELD_FIRE_RANGE};

	public static void init(World world) {

	}

	public static void updateSkills(Wizard self, EnemyPositionCalc enemyPositionCalc, Wizard[] wizards, Move move) {
		if (self.getLevel() > self.getSkills().length && self.getLevel() <= currentSkillsToLearn.length) {
			move.setSkillToLearn(currentSkillsToLearn[self.getSkills().length]);
		}
	}
}
